CREATE TABLE IF NOT EXISTS `fredstorage`
(
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `cid`       INT(10) NOT NULL,
    `daynotes`  INT(4)  NOT NULL,
    `TIMESTAMP` TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP

);
CREATE UNIQUE INDEX IF NOT EXISTS `fredstorage_cid_2` ON `fredstorage` (`cid`);
